export const data = [
    {
        questions: "what type of company CodSoft is? 1",
        option1 : "a",
        option2 : "b",
        option3 : "c",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "What is the CodSoft Company do? 2",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "what type of company CodSoft is? 3",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "What is the CodSoft Company do? 4",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "what type of company CodSoft is? 5",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "What is the CodSoft Company do? 6",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "what type of company CodSoft is? 7",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "What is the CodSoft Company do? 8",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "what type of company CodSoft is? 9",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },
    {
        questions: "What is the CodSoft Company do? 10",
        option1 : "Option 1",
        option2 : "Option 2",
        option3 : "Option 3",
        option4 : "Option 4",
        ans: 1,
    },   
     
]